### ISSUE TITLE
使用typescript来进行前端开发构建的时候报错找不到js文件

### ISSUE THREAD

**Issue by chuans** [easy-team/easywebpack#38]
`
 nodejs.Error: read webpack memory file[/Users/xxx/Documents/xxx/chasing_the_wind/app/view/index.js] content is empty, please check if the file exists
    at /Users/xxx/Documents/xxx/chasing_the_wind/node_modules/egg-webpack-react/app.js:20:17
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/chuans/Documents/chuans/chasing_the_wind/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`
这个是目前报错的信息，但是我如果吧tsx的后缀改成js或者jsx 一切正常，请问下 这个是什么问题呢

**Comment by hubcarl** [comment]
tsx 需要显示加入到 resolve.extendsions 里面
